version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/bureaux-a-partager/lucca-leaves-slack-reminder

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Get deps
          command: go get ./...

      - run:
          name: Run unit tests
          command: |
            make test | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

      - deploy:
          name: Release
          command: |
            if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
            then
              curl -sL https://git.io/goreleaser | bash
            else
              echo "Not a release, skipping build"
            fi
